### ISSUE TITLE
diskspace shows up a little weird

### ISSUE THREAD

**Issue by JamesMarcum** [Airyzz/ha-unraid-api#1]
diskSpace shows as (and I quote)
ent-Type" content="text/html; charset=utf-8">

Also, can we set it to pass any other parameters?  Disk and CPU temps, percentage full per array/disk, upload/download rates, things like that?

**Comment by Airyzz** [comment]
Hi, I'm not sure if you have the right repo. This repo only provides switches for VMs and Dockers for the [Unraid-API](https://github.com/ElectricBrainUK/UnraidAPI), whch uses MQTT. This repo not create any sensors with the kind of data you are after, so you might need to create an issue at the linked repo. 

However, on my own personal HA, I a [Glances](https://nicolargo.github.io/glances/) docker, which has an [official HA Integration](https://www.home-assistant.io/integrations/glances/), which provides lots of information about CPU Temperature, CPU Usage, Disk Space, pretty much anything you could possibly need, and it works really well so maybe you might want to look into that.

**Comment by JamesMarcum** [comment]
Holy Cheezewiz Batman!  That gives everything!
